name: system_command_runner
description: A lightweight, testable wrapper around Process.run for executing system commands with cross-platform support and easy mocking.
version: 0.1.0
homepage: https://github.com/arturograu/system_command_runner
repository: https://github.com/arturograu/system_command_runner
issue_tracker: https://github.com/arturograu/system_command_runner/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

topics:
  - system
  - command
  - process
  - shell
  - testing
  - mock
